version: '3.8'

services:
  web:
    build: .
    container_name: windi-chat
    ports:
      - "8000:80"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:13
    container_name: windi-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: default_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
